// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgsmpemhzagttymzzulg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhnc21wZW1oemFndHR5bXp6dWxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxOTMxNTEsImV4cCI6MjA3Mzc2OTE1MX0.wv5F4Pyq3dhMerPxQBTKNt9ldYRePgGBiAY2tS98Ey4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});